name = "The Boys Modded Server"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55a2c7977dfdff20154020a357cf59ffa5ba401be61e4685d7481d35b64910ba"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
