name = "The Boys Modded Server"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1b7187b6aa6cd1aebd979f448397f3a31a6d81c60631e332fa165aabffa29ed"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
