name = "The Boys Modded Server"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef2739af35e8f086e227249621053fb6db671e06d212d1ddbf21dc7f02cf921f"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
