name = "The Boys Modded Server"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d1d3c35fa7835206c0ed1e103e5d620733420496b2895ee7cb1c9847da7bffa"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
